MeCuida/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from rest_framework.authtoken.views import obtain_auth_token
from activities.views import ActivityViewSet
from appointments.views import AppointmentViewSet
from documents.views import DocumentTypeViewSet
from profiles.views import HealthProfileViewSet, PatientProfileViewSet
from .views import HomeView, LoginView, logout_view, SelfDetailView, SelfUpdateView, PasswordChangeView

router = routers.DefaultRouter()
router.register('activities', ActivityViewSet, basename='activity')
router.register('appointments', AppointmentViewSet, basename='appointment')
router.register('document_types', DocumentTypeViewSet, basename='document_type')
router.register('health_profiles', HealthProfileViewSet, basename='health_profile')
router.register('patient_profiles', PatientProfileViewSet, basename='patient_profile')

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('detail/', SelfDetailView.as_view(), name='detail'),
    path('update/', SelfUpdateView.as_view(), name='update'),
    path('password_change/', PasswordChangeView.as_view(), name='password_change'),
    path('profiles/', include('profiles.urls')),
    path('documents/', include('documents.urls')),
    path('appointments/', include('appointments.urls')),
    path('api_token/', obtain_auth_token),
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
]

profiles/urls.py
from django.urls import path
from .views import HealthListView, HealthCreateView, HealthDetailView, HealthUpdateView, HealthSoftDeleteView, PatientListView, PatientCreateView, PatientDetailView, PatientUpdateView, PatientSoftDeleteView

urlpatterns = [
    path('', HealthListView.as_view(), name='list_health'),
    path('create/', HealthCreateView.as_view(), name='create_health'),
    path('patients/', PatientListView.as_view(), name='list_patient'),
    path('<slug:slug>/', HealthDetailView.as_view(), name='detail_health'),
    path('update/<slug:slug>/', HealthUpdateView.as_view(), name='update_health'),
    path('delete/<slug:slug>/', HealthSoftDeleteView.as_view(), name='delete_health'),
    path('patients/create/', PatientCreateView.as_view(), name='create_patient'),
    path('patients/<slug:slug>/', PatientDetailView.as_view(), name='detail_patient'),
    path('patients/update/<slug:slug>/', PatientUpdateView.as_view(), name='update_patient'),
    path('patients/delete/<slug:slug>/', PatientSoftDeleteView.as_view(), name='delete_patient')
]

activities/models.py
from django.db import models
from base_classes.models import Base
from profiles.models import PatientProfile

class Activity(Base):
    SHIFTS = [('mat','Matutino'), ('ves','Vespertino'), ('not','Noturno'), ('mad','Madrugada')]
    ACT = [('ref','Refeição'), ('fis','Atividade Física'), ('gli','Medição de Glicemia Capilar'), ('pre','Medição de Pressão Arterial'), ('med','Uso de Medicamento')]
    patient = models.ForeignKey(PatientProfile, on_delete=models.CASCADE)
    date = models.DateField()
    shift = models.CharField(max_length=3, choices=SHIFTS)
    activitytype = models.CharField(max_length=3, choices=ACT)
    picture = models.FileField(blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    value = models.IntegerField(blank=True, null=True)

    class Meta:
        ordering = ['-date']
        verbose_name = 'Atividade'
        verbose_name_plural = 'Atividades'

    def save(self, *args, **kwargs):
        slug = str(self.patient)+' '+str(self.activitytype)+' '+self.date.strftime('%d-%m-%Y')
        super().save(field=slug, *args, **kwargs)

    def __str__(self):
        return str(self.activitytype)+" - "+self.date.strftime('%d-%m-%Y')+" - "+str(self.shift)

profiles/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from rest_framework.authtoken.models import Token
from base_classes.models import Base
from documents.models import DocumentType

UserModel = get_user_model()

@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

class Profile(Base):
    user = models.OneToOneField(UserModel, null=True, on_delete=models.SET_NULL)
    name = models.CharField(max_length=500)
    cpf = models.CharField(max_length=14)

    class Meta:
        abstract = True

    def save(self, *args, **kwargs):
        super().save(field=self.name, *args, **kwargs)

class HealthProfile(Profile):
    SPEC = [('enf','Enfermeiro'), ('med','Médico'), ('psi','Psicólogo'), ('edf','Educação Física')]
    specialty = models.CharField(max_length=3, choices=SPEC)
    documentnumber = models.CharField(max_length=50)
    documenttype = models.ForeignKey(DocumentType, on_delete=models.CASCADE, related_name='health')
    admin = models.BooleanField(default=False)

    class Meta:
        ordering = ['-pk']
        verbose_name = 'Profissional da Saúde'
        verbose_name_plural = 'Profissionais da Saúde'

    def get_absolute_url(self):
        return reverse('list_health')

    def __str__(self):
        return self.name+" ("+self.get_specialty_display()+")"

class PatientProfile(Profile):
    health = models.ManyToManyField(HealthProfile)

    class Meta:
        ordering = ['-pk']
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'

    def get_absolute_url(self):
        return reverse('list_patient')

    def __str__(self):
        return self.name

profiles/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.password_validation import validate_password
from documents.models import DocumentType
from .models import HealthProfile, PatientProfile

UserModel = get_user_model()

class ProfileAbstractForm(forms.ModelForm):
    name = forms.CharField(label='Nome Completo')
    cpf = forms.CharField(label='CPF', max_length=14)
    username = forms.CharField(label='Nome de Usuário', max_length=150)
    email = forms.EmailField(label='E-Mail')


# Profissionais de Saúde
class HealthAbstractForm(ProfileAbstractForm):
    specialty = forms.ChoiceField(label='Área de Atuação', choices=HealthProfile.SPEC)
    documenttype = forms.ModelChoiceField(label='Documento', queryset=DocumentType.objects.filter(status=True), empty_label='Selecionar')
    documentnumber = forms.CharField(label='')

    class Meta:
        model = HealthProfile
        fields = ['name', 'cpf', 'specialty', 'admin', 'documenttype', 'documentnumber']

class HealthUpdateForm(HealthAbstractForm):
    def save(self):
        self.user = self.instance.user
        self.user.username = self.cleaned_data['username']
        self.user.email = self.cleaned_data['email']

        self.user.save()
        return super().save()

class HealthCreateForm(HealthAbstractForm):
    password = forms.CharField(label='Senha', widget=forms.PasswordInput())
    confirm = forms.CharField(label='Confirmar Senha', widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm = cleaned_data.get("confirm")

        if password != confirm:
            self.add_error('confirm', "A confirmação de senha não corresponde!")

        validate_password(password)
        return cleaned_data

    def save(self):
        self.user = UserModel()
        self.user.username = self.cleaned_data['username']
        self.user.email = self.cleaned_data['email']
        self.user.set_password(self.cleaned_data['password'])

        self.instance.user = self.user
        self.user.save()
        return super().save()


# Pacientes
class PatientAbstractForm(ProfileAbstractForm):
    health = forms.ModelMultipleChoiceField(label='Profissional de Saúde', queryset=HealthProfile.objects.filter(status=True))

    class Meta:
        model = PatientProfile
        fields = ['name', 'cpf', 'health']

class PatientUpdateForm(PatientAbstractForm):
    def save(self):
        self.user = self.instance.user
        self.user.username = self.cleaned_data['username']
        self.user.email = self.cleaned_data['email']

        self.user.save()
        return super().save()

class PatientCreateForm(PatientAbstractForm):
    password = forms.CharField(label='Senha', widget=forms.PasswordInput())
    confirm = forms.CharField(label='Confirmar Senha', widget=forms.PasswordInput())

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm = cleaned_data.get("confirm")

        if password != confirm:
            self.add_error('confirm', "A confirmação de senha não corresponde!")

        validate_password(password)
        return cleaned_data

    def save(self):
        self.user = UserModel()
        self.user.username = self.cleaned_data['username']
        self.user.email = self.cleaned_data['email']
        self.user.set_password(self.cleaned_data['password'])

        self.instance.user = self.user
        self.user.save()
        return super().save()

profiles/views.py
from django.views.generic import ListView, CreateView, DetailView, UpdateView
from django.urls import reverse_lazy
from rest_framework.viewsets import ReadOnlyModelViewSet, GenericViewSet
from rest_framework.mixins import RetrieveModelMixin, UpdateModelMixin
from rest_framework.permissions import IsAuthenticated
from MeCuida.views import user_context
from base_classes.mixins import SuperorAdminMixin, NotPatientMixin
from base_classes.views import SoftDeleteView
from activities.models import Activity
from .serializers import HealthProfileSerializer, PatientProfileSerializer, HealthProfileFilter, PatientProfileFilter
from .models import HealthProfile, PatientProfile
from .forms import HealthCreateForm, HealthUpdateForm, PatientCreateForm, PatientUpdateForm


# Profissionais de Saúde
class HealthListView(SuperorAdminMixin, ListView):
    queryset = HealthProfile.objects.filter(status=True)
    template_name = 'health_list.html'

class HealthCreateView(SuperorAdminMixin, CreateView):
    queryset = HealthProfile.objects.filter(status=True)
    form_class = HealthCreateForm
    template_name = 'health_form.html'

class HealthDetailView(SuperorAdminMixin, DetailView):
    queryset = HealthProfile.objects.filter(status=True)
    template_name = 'health_detail.html'

class HealthUpdateView(SuperorAdminMixin, UpdateView):
    queryset = HealthProfile.objects.filter(status=True)
    form_class = HealthUpdateForm
    template_name = 'health_form.html'

    def get_initial(self):
        initial = super().get_initial()
        health = self.get_object()
        user = health.user
        initial['username'] = user.username
        initial['email'] = user.email
        return initial

class HealthSoftDeleteView(SuperorAdminMixin, SoftDeleteView):
    queryset = HealthProfile.objects.filter(status=True)
    template_name = 'health_softdelete.html'
    success_url = reverse_lazy('list_health')

class HealthProfileViewSet(ReadOnlyModelViewSet):
    queryset = HealthProfile.objects.filter(status=True)
    permission_classes = [IsAuthenticated]
    serializer_class = HealthProfileSerializer
    filter_class = HealthProfileFilter
    lookup_field = 'slug'

    def get_queryset(self):
        try:
            patient = PatientProfile.objects.get(user=self.request.user)
            return HealthProfile.objects.filter(patientprofile=patient, status=True)
        except:
            return HealthProfile.objects.none()

    def get_object(self):
        obj = super().get_object()
        try:
            patient = PatientProfile.objects.get(user=self.request.user)
        except:
            patient = None
        if not obj.status or not obj in patient.health.all():
            raise Http404
        return obj

# Pacientes
class PatientListView(NotPatientMixin, ListView):
    queryset = PatientProfile.objects.filter(status=True)
    template_name = 'patient_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        aux = user_context(self.request)
        if aux['priority']>=3:
            return context
        context['object_list'] = self.queryset.filter(health=aux['profile'])
        return context

class PatientCreateView(NotPatientMixin, CreateView):
    queryset = PatientProfile.objects.filter(status=True)
    form_class = PatientCreateForm
    template_name = 'patient_form.html'

class PatientDetailView(NotPatientMixin, DetailView):
    queryset = PatientProfile.objects.filter(status=True)
    template_name = 'patient_detail.html'

    def dispatch(self, request, *args, **kwargs):
        temp = super().dispatch(request, *args, **kwargs)
        context = self.get_context_data()
        aux = user_context(self.request)
        if aux['priority']<=2 and not aux['profile'] in context['object'].health.all():
            return self.handle_no_permission()
        return temp

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['activities'] = Activity.objects.filter(status=True, patient=self.object).order_by('-date')
        return context

class PatientUpdateView(NotPatientMixin, UpdateView):
    queryset = PatientProfile.objects.filter(status=True)
    form_class = PatientUpdateForm
    template_name = 'patient_form.html'

    def dispatch(self, request, *args, **kwargs):
        temp = super().dispatch(request, *args, **kwargs)
        context = self.get_context_data()
        aux = user_context(self.request)
        if aux['priority']<=2 and not aux['profile'] in context['object'].health.all():
            return self.handle_no_permission()
        return temp

    def get_initial(self):
        initial = super().get_initial()
        patient = self.get_object()
        user = patient.user
        initial['username'] = user.username
        initial['email'] = user.email
        return initial

class PatientSoftDeleteView(NotPatientMixin, SoftDeleteView):
    queryset = PatientProfile.objects.filter(status=True)
    template_name = 'patient_softdelete.html'
    success_url = reverse_lazy('list_patient')

    def dispatch(self, request, *args, **kwargs):
        temp = super().dispatch(request, *args, **kwargs)
        context = self.get_context_data()
        aux = user_context(self.request)
        if aux['priority']<=2 and not aux['profile'] in context['object'].health.all():
            return self.handle_no_permission()
        return temp

class PatientProfileViewSet(RetrieveModelMixin, UpdateModelMixin, GenericViewSet):
    queryset = PatientProfile.objects.filter(status=True)
    permission_classes = [IsAuthenticated]
    serializer_class = PatientProfileSerializer
    filter_class = PatientProfileFilter

    def list(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def get_object(self):
        try:
            patient = PatientProfile.objects.get(user=self.request.user)
        except:
            patient = None
        if not patient:
            raise Http404
        return patient

profiles/templates/health_detail.html
{% extends "health_list.html" %}

{% block back %}href='{% url "list_health" %}'{% endblock back %}

{% block health %}
    {{ object.name }} <i class="material-icons"><a href='{% url "update_health" object.slug %}'>settings</a></i></h3>
    CPF {{ object.cpf }}
{% endblock health %}

profiles/templates/health_form.html
{% extends "health_list.html" %}

{% block back %}href='{% url "list_health" %}'{% endblock back %}

{% block health %}
    Registrar Profissional da Saúde </h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        {% if form_2 %}
            {{ form_2.as_p }}
        {% endif %}
        <button type="submit">Registrar</button>
    </form>
{% endblock health %}

profiles/templates/health_list.html
{% extends "layout.html" %}

{% block content %}
    <h3><i class="material-icons"><a {% block back %}href='{% url "home" %}'{% endblock back %}>arrow_back</a></i>
    {% block health %}
    Profissionais da Saúde <i class="material-icons"><a href='{% url "create_health" %}'>add</a></i></h3>
    <ul class="list-group list-group-flush bg-transparent w-25">
        {% for health in object_list %}
            <li class="list-group-item bg-transparent d-flex justify-content-between align-items-center">
                <a href='{% url "detail_health" health.slug %}'>{{ health.name }}</a>
                <span class="self-align-end"><i class="material-icons"><a href='{% url "delete_health" health.slug %}'>delete</a></i></span>
            </li>
        {% endfor %}
    </ul>
    {% endblock health %}
{% endblock content %}

profiles/templates/health_softdelete.html
{% extends "health_list.html" %}

{% block back %}href='{% url "list_health" %}'{% endblock back %}

{% block health %}
    Deletar Profissional de Saúde</h3>
    <form method="post">
        {% csrf_token %}
        Você tem certeza que quer deletar {{ object.name }}?
        <button type="submit">Sim</button>
    </form>
{% endblock health %}

profiles/templates/patient_detail.html
{% extends "patient_list.html" %}

{% block back %}href='{% url "list_patient" %}'{% endblock back %}

{% block patient %}
    {{ object.name }} <i class="material-icons"><a href='{% url "update_patient" object.slug %}'>settings</a></i></h3>
    CPF {{ object.cpf }}
    <br>
    <br>
    <h5>Atividades</h5>
    <ul class="list-group list-group-flush bg-transparent w-25">
        {% for activity in activities %}
            <li class="list-group-item bg-transparent d-flex justify-content-between align-items-center">
                ({{ activity.date }}){{ activity.get_activitytype_display }}{% if activity.description %} - {{ activity.description }}{% endif %}
            </li>
        {% endfor %}
    </ul>
{% endblock patient %}

profiles/templates/patient_form.html
{% extends "patient_list.html" %}

{% block back %}href='{% url "list_patient" %}'{% endblock back %}

{% block patient %}
    Registrar Paciente </h3>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <br>
        <button type="submit">Registrar</button>
    </form>
{% endblock patient %}

profiles/templates/patient_list.html
{% extends "layout.html" %}

{% block content %}
    <h3><i class="material-icons"><a {% block back %}href='{% url "home" %}'{% endblock back %}>arrow_back</a></i>
    {% block patient %}
        Pacientes <i class="material-icons"><a href='{% url "create_patient" %}'>add</a></i></h3>
        <ul class="list-group list-group-flush bg-transparent w-25">
            {% for patient in object_list %}
                <li class="list-group-item bg-transparent d-flex justify-content-between align-items-center">
                    <a href='{% url "detail_patient" patient.slug %}'>{{ patient.name }}</a>
                    <span class="self-align-end"><i class="material-icons"><a href='{% url "delete_patient" patient.slug %}'>delete</a></i></span>
                </li>
            {% endfor %}
        </ul>
    {% endblock patient %}
{% endblock content %}

profiles/templates/patient_softdelete.html
{% extends "patient_list.html" %}

{% block back %}href='{% url "list_patient" %}'{% endblock back %}

{% block patient %}
    Deletar Paciente</h3>
    <form method="post">
        {% csrf_token %}
        Você tem certeza que quer deletar {{ object.name }}?
        <button type="submit">Sim</button>
    </form>
{% endblock patient %}